In [1]:
import numpy as np

# Set random seed for reproducibility
np.random.seed(42)

In [2]:
# Create a 4x7 matrix with random numbers in [-0.5, 0.5]
# This represents word embeddings for 4 words, each with dimension 7
X0 = np.random.uniform(-0.5, 0.5, size=(4, 7))

print("Part (a): Word Embeddings Matrix X0")
print("Shape:", X0.shape)
print(X0)
print("\n" + "="*80 + "\n")

Part (a): Word Embeddings Matrix X0
Shape: (4, 7)
[[-0.12545988  0.45071431  0.23199394  0.09865848 -0.34398136 -0.34400548
  -0.44191639]
 [ 0.36617615  0.10111501  0.20807258 -0.47941551  0.46990985  0.33244264
  -0.28766089]
 [-0.31817503 -0.31659549 -0.19575776  0.02475643 -0.06805498 -0.20877086
   0.11185289]
 [-0.36050614 -0.20785535 -0.13363816 -0.04393002  0.28517596 -0.30032622
   0.01423444]]




In [3]:
# Create positional embeddings using the actual formula from transformer papers
# For position pos and dimension i:
# PE(pos, 2i) = sin(pos / 10000^(2i/d_model))
# PE(pos, 2i+1) = cos(pos / 10000^(2i/d_model))

def create_positional_encoding(num_positions, d_model):
    """
    Create positional encodings for transformer
    num_positions: number of positions (words) in sequence
    d_model: dimension of embeddings
    """
    P = np.zeros((num_positions, d_model))

    for pos in range(num_positions):
        for i in range(0, d_model, 2):
            # Calculate the denominator for the sinusoidal functions
            denominator = np.power(10000, (2 * i) / d_model)

            # Apply sin to even indices
            P[pos, i] = np.sin(pos / denominator)

            # Apply cos to odd indices (if within bounds)
            if i + 1 < d_model:
                P[pos, i + 1] = np.cos(pos / denominator)

    return P

# Create positional embeddings for 4 words with dimension 7
P = create_positional_encoding(4, 7)

print("Part (b): Positional Embeddings Matrix P")
print("Shape:", P.shape)
print(P)
print("\n" + "="*80 + "\n")

Part (b): Positional Embeddings Matrix P
Shape: (4, 7)
[[ 0.00000000e+00  1.00000000e+00  0.00000000e+00  1.00000000e+00
   0.00000000e+00  1.00000000e+00  0.00000000e+00]
 [ 8.41470985e-01  5.40302306e-01  5.17945152e-03  9.99986587e-01
   2.68269579e-05  1.00000000e+00  1.38949549e-07]
 [ 9.09297427e-01 -4.16146837e-01  1.03587641e-02  9.99946347e-01
   5.36539159e-05  9.99999999e-01  2.77899099e-07]
 [ 1.41120008e-01 -9.89992497e-01  1.55377988e-02  9.99879281e-01
   8.04808738e-05  9.99999997e-01  4.16848648e-07]]




In [4]:
# Following slide 20: p + x vectors
# Add word embeddings X0 and positional embeddings P element-wise
X = X0 + P

print("Part (c): Combined Matrix X = X0 + P")
print("Shape:", X.shape)
print(X)
print("\n" + "="*80 + "\n")

Part (c): Combined Matrix X = X0 + P
Shape: (4, 7)
[[-0.12545988  1.45071431  0.23199394  1.09865848 -0.34398136  0.65599452
  -0.44191639]
 [ 1.20764713  0.64141732  0.21325203  0.52057108  0.46993668  1.33244264
  -0.28766075]
 [ 0.59112239 -0.73274233 -0.18539899  1.02470278 -0.06800133  0.79122914
   0.11185317]
 [-0.21938613 -1.19784785 -0.11810036  0.95594927  0.28525644  0.69967378
   0.01423486]]




In [5]:
# From slide 20: Before computing attention, we project to higher dimension
# Original dimension e = 7, projecting to e' = 13
# We need three weight matrices to create Q, K, V

e = 7   # Original embedding dimension
e_prime = 13  # Projected dimension

# Create three weight matrices with random values in [-0.5, 0.5]
# W^Q: maps from dimension 7 to dimension 13
W_Q = np.random.uniform(-0.5, 0.5, size=(e, e_prime))

# W^K: maps from dimension 7 to dimension 13
W_K = np.random.uniform(-0.5, 0.5, size=(e, e_prime))

# W^V: maps from dimension 7 to dimension 13
W_V = np.random.uniform(-0.5, 0.5, size=(e, e_prime))

print("Part (d): Weight Matrices for Query, Key, Value")
print("\nW^Q (Query weights) - Shape:", W_Q.shape)
print(W_Q)
print("\nW^K (Key weights) - Shape:", W_K.shape)
print(W_K)
print("\nW^V (Value weights) - Shape:", W_V.shape)
print(W_V)
print("\n" + "="*80 + "\n")

Part (d): Weight Matrices for Query, Key, Value

W^Q (Query weights) - Shape: (7, 13)
[[ 0.09241457 -0.45354959  0.10754485 -0.32947588 -0.43494841  0.44888554
   0.46563203  0.30839735 -0.19538623 -0.40232789  0.18423303 -0.05984751
  -0.37796177]
 [-0.00482309 -0.46561148  0.4093204  -0.24122002  0.16252228 -0.18828892
   0.02006802  0.04671028 -0.31514554  0.46958463  0.27513282  0.43949894
   0.39482735]
 [ 0.09789998  0.42187424 -0.4115075  -0.30401714 -0.45477271 -0.17466967
  -0.11132271 -0.22865097  0.32873751 -0.14324667 -0.21906549  0.04269608
  -0.35907578]
 [ 0.30219698 -0.42544936  0.48688694  0.27224477 -0.30128432 -0.49447788
   0.31546143  0.20685734  0.22900717  0.27127035 -0.42595535 -0.14153427
  -0.38413094]
 [ 0.36310343  0.12329813 -0.16910198 -0.43644165 -0.18901768 -0.17481668
   0.22960618  0.13755747  0.38721274 -0.02778507 -0.38040575  0.21324479
   0.26078505]
 [ 0.0612772   0.27096718 -0.0062044   0.02273283 -0.07245898 -0.47458087
  -0.39210857 -0.46857081

In [6]:
# From slide 14 and 20: Q = XW^Q, K = XW^K, V = XW^V
# Following slide 10: We treat X as having words in rows (4 words × 7 dimensions)
# Matrix multiplication: (4×7) × (7×13) = (4×13)

Q = X @ W_Q  # Query matrix
K = X @ W_K  # Key matrix
V = X @ W_V  # Value matrix

print("Part (e): Query, Key, and Value Matrices")
print("\nQuery Matrix Q - Shape:", Q.shape)
print(Q)
print("\nKey Matrix K - Shape:", K.shape)
print(K)
print("\nValue Matrix V - Shape:", V.shape)
print(V)
print("\n" + "="*80 + "\n")

Part (e): Query, Key, and Value Matrices

Query Matrix Q - Shape: (4, 13)
[[ 0.29103218 -0.96570974  1.19371602  0.27194848 -0.03577297 -1.0147321
  -0.23463875 -0.28756883 -0.20747003  0.72013182 -0.14049891  0.83202224
  -0.31277777]
 [ 0.56476624 -0.63241171  0.54840577 -0.52884628 -0.79973422 -0.49038722
   0.1775025  -0.18701495  0.07657051 -0.44127442 -0.12419395  0.87848593
  -0.80416152]
 [ 0.36344277 -0.20650738  0.31510853  0.31767534 -0.66860235 -0.47250365
   0.32663595  0.0567962   0.38566253 -0.38082878 -0.42194414 -0.23744364
  -1.01196818]
 [ 0.40800177  0.42910065 -0.05629802  0.54277018 -0.44116804 -0.71174684
  -0.01421404 -0.18308253  0.80825336 -0.33051604 -0.8494992  -0.31213376
  -0.81026125]]

Key Matrix K - Shape: (4, 13)
[[-1.12008251 -0.06826627  0.626697   -0.26883548  0.48677139  0.37718441
  -1.10333017  0.99383526  1.03052525 -0.21187609 -0.61460467 -0.16499536
   0.14682857]
 [-1.09558654  0.51679339  0.90781302 -0.25904476 -0.43045228 -0.24955388
  -1.1

In [7]:
# From slides 14-15 and 21:
# Head = Attention(Q, K, V) = [SoftMax(QK^T / sqrt(e'))]V

def softmax(x):
    """
    Compute softmax along the last axis
    Subtracting max for numerical stability
    """
    exp_x = np.exp(x - np.max(x, axis=-1, keepdims=True))
    return exp_x / np.sum(exp_x, axis=-1, keepdims=True)

# Step 1: Compute QK^T (from slide 10: matrix multiplication)
# Q is (4×13), K^T is (13×4), result is (4×4)
QK_T = Q @ K.T

print("Part (f): Computing Attention-Weighted Output (Head)")
print("\nStep 1: QK^T - Shape:", QK_T.shape)
print(QK_T)

# Step 2: Divide by sqrt(e') for scaled dot-product attention
# From slide 14: this is the "scaled" part
scaling_factor = np.sqrt(e_prime)
scaled_scores = QK_T / scaling_factor

print("\nStep 2: QK^T / sqrt(e') where sqrt(e')=", scaling_factor)
print("Scaled Attention Scores - Shape:", scaled_scores.shape)
print(scaled_scores)

# Step 3: Apply softmax row-wise (from slide 11 and 15)
# Each row represents attention scores for one query word
attention_weights = softmax(scaled_scores)

print("\nStep 3: SoftMax(QK^T / sqrt(e'))")
print("Attention Weights - Shape:", attention_weights.shape)
print(attention_weights)
print("\nNote: Each row sums to 1.0, representing attention distribution")
print("Row sums:", np.sum(attention_weights, axis=1))

# Step 4: Multiply attention weights by V (from slide 15 and 21)
# attention_weights is (4×4), V is (4×13), result is (4×13)
# This weights each value vector by the attention scores
Head_output = attention_weights @ V

print("\nStep 4: [SoftMax(QK^T / sqrt(e'))] × V")
print("Head Output (Attention-Weighted Input) - Shape:", Head_output.shape)
print(Head_output)

print("\n" + "="*80)
print("FINAL RESULT: Single-Head Attention Output")
print("="*80)
print("Shape:", Head_output.shape)
print(Head_output)
print("\nThis matrix contains the attention-weighted representation of the 4 words,")
print("where each word (row) is now represented as a weighted combination of all words")
print("based on their relevance/attention scores.")

Part (f): Computing Attention-Weighted Output (Head)

Step 1: QK^T - Shape: (4, 4)
[[-0.47536726 -0.33851244 -0.25888984 -0.2822365 ]
 [-1.07380202 -0.09020594 -0.37456633 -1.2725073 ]
 [-0.46048838  0.53284091  0.28551478 -1.04760789]
 [ 0.04062591  1.22833922  1.18792759 -0.05268729]]

Step 2: QK^T / sqrt(e') where sqrt(e')= 3.605551275463989
Scaled Attention Scores - Shape: (4, 4)
[[-0.13184316 -0.09388646 -0.07180312 -0.07827832]
 [-0.2978191  -0.02501863 -0.10388601 -0.35293003]
 [-0.1277165   0.14778348  0.07918755 -0.29055415]
 [ 0.0112676   0.34068     0.32947183 -0.01461282]]

Step 3: SoftMax(QK^T / sqrt(e'))
Attention Weights - Shape: (4, 4)
[[0.24063968 0.24994912 0.25553023 0.25388097]
 [0.22351197 0.29361384 0.27134689 0.21152729]
 [0.22743903 0.2995802  0.2797192  0.19326157]
 [0.21100342 0.29332663 0.29005733 0.20561262]]

Note: Each row sums to 1.0, representing attention distribution
Row sums: [1. 1. 1. 1.]

Step 4: [SoftMax(QK^T / sqrt(e'))] × V
Head Output (Attention